<?php
function mk_enum($a) {
	$r = array();
	foreach ($a as $k) {
		if (trim($k) == '') {
			$r[NULL] = '';
		} else {
			$r[$k] = $k;
		}
	}
	return $r;
}

 

$__otatest2_addition_enum = array
(
	'','特別','普通',
);




$__otatest2_exam_enum = array
(
	'N/A','異常なし','所見あり','再検査','不明',
);
$__otatest2_hantei_enum = array
(
	'-','A','B','C(1)','C(2)','C(3)','D','E','F','G'
);
//1020-2012
$__otatest2_n_enum = array
(
'0'=>'-','1'=>'Ab',
);
$__otatest2_plus_enum = array
(
	'N/A','(-)','(+)', 
);
$__otatest2_abo_enum = array
(
   'N/A','A','B','O','AB',
);

 $__otatest2_rh_enum = array
 (
 	'N/A','Rh+','Rh-', 
);
$__otatest2_np_enum = array
(
	'N/A','NEGATIVE','POSITIVE', 
);
//0715-2014 added test template

$__otatest2_report_enum = array
(
'1'=>'Japanese', '2'=>'English','3'=>'test Japanese','4'=>'test English' 
);
//0820-2014

$__otatest2_all_cols = array(
array('Column' =>'cc50', 'Draw' => 'enum', 'Enum' => $__otatest2_n_enum,),
array('Column' =>'aa1', 'Draw' => 'enum', 'Enum' => $__otatest2_n_enum,),
array('Column' =>'aa10', 'Draw' => 'enum', 'Enum' => $__otatest2_n_enum,),
array('Column' =>'aa1000', 'Draw' => 'enum', 'Enum' => $__otatest2_n_enum,),
array('Column' =>'aa1001', 'Draw' => 'enum', 'Enum' => $__otatest2_n_enum,),
array('Column' =>'aa1003', 'Draw' => 'enum', 'Enum' => $__otatest2_n_enum,),
array('Column' =>'aa1005', 'Draw' => 'enum', 'Enum' => $__otatest2_n_enum,),
array('Column' =>'aa1006', 'Draw' => 'enum', 'Enum' => $__otatest2_n_enum,),
array('Column' =>'aa1007', 'Draw' => 'enum', 'Enum' => $__otatest2_n_enum,),
array('Column' =>'aa11', 'Draw' => 'enum', 'Enum' => $__otatest2_n_enum,),
array('Column' =>'aa12', 'Draw' => 'enum', 'Enum' => $__otatest2_n_enum,),
array('Column' =>'aa13', 'Draw' => 'enum', 'Enum' => $__otatest2_n_enum,),
array('Column' =>'aa14', 'Draw' => 'enum', 'Enum' => $__otatest2_n_enum,),
array('Column' =>'aa15', 'Draw' => 'enum', 'Enum' => $__otatest2_n_enum,),
array('Column' =>'aa16', 'Draw' => 'enum', 'Enum' => $__otatest2_n_enum,),
array('Column' =>'aa17', 'Draw' => 'enum', 'Enum' => $__otatest2_n_enum,),
array('Column' =>'aa18', 'Draw' => 'enum', 'Enum' => $__otatest2_n_enum,),
array('Column' =>'aa19', 'Draw' => 'enum', 'Enum' => $__otatest2_n_enum,),
array('Column' =>'aa2', 'Draw' => 'enum', 'Enum' => $__otatest2_n_enum,),
array('Column' =>'aa20', 'Draw' => 'enum', 'Enum' => $__otatest2_n_enum,),
array('Column' =>'aa2001', 'Draw' => 'enum', 'Enum' => $__otatest2_n_enum,),
array('Column' =>'aa2002', 'Draw' => 'enum', 'Enum' => $__otatest2_n_enum,),
array('Column' =>'aa2003', 'Draw' => 'enum', 'Enum' => $__otatest2_n_enum,),
array('Column' =>'aa2004', 'Draw' => 'enum', 'Enum' => $__otatest2_n_enum,),
array('Column' =>'aa2005', 'Draw' => 'enum', 'Enum' => $__otatest2_n_enum,),
array('Column' =>'aa2006', 'Draw' => 'enum', 'Enum' => $__otatest2_n_enum,),
array('Column' =>'aa21', 'Draw' => 'enum', 'Enum' => $__otatest2_n_enum,),
array('Column' =>'aa22', 'Draw' => 'enum', 'Enum' => $__otatest2_n_enum,),
array('Column' =>'aa23', 'Draw' => 'enum', 'Enum' => $__otatest2_n_enum,),
array('Column' =>'aa24', 'Draw' => 'enum', 'Enum' => $__otatest2_n_enum,),
array('Column' =>'aa25', 'Draw' => 'enum', 'Enum' => $__otatest2_n_enum,),
array('Column' =>'aa26', 'Draw' => 'enum', 'Enum' => $__otatest2_n_enum,),
array('Column' =>'aa27', 'Draw' => 'enum', 'Enum' => $__otatest2_n_enum,),
array('Column' =>'aa28', 'Draw' => 'enum', 'Enum' => $__otatest2_n_enum,),
array('Column' =>'aa29', 'Draw' => 'enum', 'Enum' => $__otatest2_n_enum,),
array('Column' =>'aa3', 'Draw' => 'enum', 'Enum' => $__otatest2_n_enum,),
array('Column' =>'aa30', 'Draw' => 'enum', 'Enum' => $__otatest2_n_enum,),
array('Column' =>'aa31', 'Draw' => 'enum', 'Enum' => $__otatest2_n_enum,),
array('Column' =>'aa32', 'Draw' => 'enum', 'Enum' => $__otatest2_n_enum,),
array('Column' =>'aa33', 'Draw' => 'enum', 'Enum' => $__otatest2_n_enum,),
array('Column' =>'aa34', 'Draw' => 'enum', 'Enum' => $__otatest2_n_enum,),
array('Column' =>'aa35', 'Draw' => 'enum', 'Enum' => $__otatest2_n_enum,),
array('Column' =>'aa36', 'Draw' => 'enum', 'Enum' => $__otatest2_n_enum,),
array('Column' =>'aa37', 'Draw' => 'enum', 'Enum' => $__otatest2_n_enum,),
array('Column' =>'aa38', 'Draw' => 'enum', 'Enum' => $__otatest2_n_enum,),
array('Column' =>'aa39', 'Draw' => 'enum', 'Enum' => $__otatest2_n_enum,),
array('Column' =>'aa4', 'Draw' => 'enum', 'Enum' => $__otatest2_n_enum,),
array('Column' =>'aa40', 'Draw' => 'enum', 'Enum' => $__otatest2_n_enum,),
array('Column' =>'aa41', 'Draw' => 'enum', 'Enum' => $__otatest2_n_enum,),
array('Column' =>'aa42', 'Draw' => 'enum', 'Enum' => $__otatest2_n_enum,),
array('Column' =>'aa43', 'Draw' => 'enum', 'Enum' => $__otatest2_n_enum,),
array('Column' =>'aa44', 'Draw' => 'enum', 'Enum' => $__otatest2_n_enum,),
array('Column' =>'aa45', 'Draw' => 'enum', 'Enum' => $__otatest2_n_enum,),
array('Column' =>'aa46', 'Draw' => 'enum', 'Enum' => $__otatest2_n_enum,),
array('Column' =>'aa47', 'Draw' => 'enum', 'Enum' => $__otatest2_n_enum,),
array('Column' =>'aa48', 'Draw' => 'enum', 'Enum' => $__otatest2_n_enum,),
array('Column' =>'aa49', 'Draw' => 'enum', 'Enum' => $__otatest2_n_enum,),
array('Column' =>'aa5', 'Draw' => 'enum', 'Enum' => $__otatest2_n_enum,),
array('Column' =>'aa50', 'Draw' => 'enum', 'Enum' => $__otatest2_n_enum,),
array('Column' =>'aa51', 'Draw' => 'enum', 'Enum' => $__otatest2_n_enum,),
array('Column' =>'aa52', 'Draw' => 'enum', 'Enum' => $__otatest2_n_enum,),
array('Column' =>'aa53', 'Draw' => 'enum', 'Enum' => $__otatest2_n_enum,),
array('Column' =>'aa54', 'Draw' => 'enum', 'Enum' => $__otatest2_n_enum,),
array('Column' =>'aa55', 'Draw' => 'enum', 'Enum' => $__otatest2_n_enum,),
array('Column' =>'aa56', 'Draw' => 'enum', 'Enum' => $__otatest2_n_enum,),
array('Column' =>'aa57', 'Draw' => 'enum', 'Enum' => $__otatest2_n_enum,),
array('Column' =>'aa58', 'Draw' => 'enum', 'Enum' => $__otatest2_n_enum,),
array('Column' =>'aa59', 'Draw' => 'enum', 'Enum' => $__otatest2_n_enum,),
array('Column' =>'aa6', 'Draw' => 'enum', 'Enum' => $__otatest2_n_enum,),
array('Column' =>'aa7', 'Draw' => 'enum', 'Enum' => $__otatest2_n_enum,),
array('Column' =>'aa8', 'Draw' => 'enum', 'Enum' => $__otatest2_n_enum,),
array('Column' =>'aa80', 'Draw' => 'enum', 'Enum' => $__otatest2_n_enum,),
array('Column' =>'aa81', 'Draw' => 'enum', 'Enum' => $__otatest2_n_enum,),
array('Column' =>'aa82', 'Draw' => 'enum', 'Enum' => $__otatest2_n_enum,),
array('Column' =>'aa83', 'Draw' => 'enum', 'Enum' => $__otatest2_n_enum,),
array('Column' =>'aa84', 'Draw' => 'enum', 'Enum' => $__otatest2_n_enum,),
array('Column' =>'aa85', 'Draw' => 'enum', 'Enum' => $__otatest2_n_enum,),
array('Column' =>'aa86', 'Draw' => 'enum', 'Enum' => $__otatest2_n_enum,),
array('Column' =>'aa87', 'Draw' => 'enum', 'Enum' => $__otatest2_n_enum,),
array('Column' =>'aa88', 'Draw' => 'enum', 'Enum' => $__otatest2_n_enum,),
array('Column' =>'aa89', 'Draw' => 'enum', 'Enum' => $__otatest2_n_enum,),
array('Column' =>'aa9', 'Draw' => 'enum', 'Enum' => $__otatest2_n_enum,),
array('Column' =>'aa90', 'Draw' => 'enum', 'Enum' => $__otatest2_n_enum,),
array('Column' =>'aa91', 'Draw' => 'enum', 'Enum' => $__otatest2_n_enum,),
array('Column' =>'aa94', 'Draw' => 'enum', 'Enum' => $__otatest2_n_enum,),
array('Column' =>'c1002', 'Draw' => 'textarea','Option' =>array('vocab' => array('c1002'),'cols' => 20,'rows'=>3),),
array('Column' =>'c500', 'Draw' => 'textarea','Option' =>array('vocab' => array('c500'),'cols' => 20,'rows'=>3),),
array('Column' =>'c501', 'Draw' => 'textarea','Option' =>array('vocab' => array('c501'),'cols' => 20,'rows'=>3),),
array('Column' =>'c502', 'Draw' => 'textarea','Option' =>array('vocab' => array('c502'),'cols' => 20,'rows'=>3),),
array('Column' =>'c503', 'Draw' => 'textarea','Option' =>array('vocab' => array('c503'),'cols' => 20,'rows'=>3),),
array('Column' =>'c504', 'Draw' => 'textarea','Option' =>array('vocab' => array('c504'),'cols' => 20,'rows'=>3),),
array('Column' =>'c505', 'Draw' => 'textarea','Option' =>array('vocab' => array('c505'),'cols' => 20,'rows'=>3),),
array('Column' =>'c506', 'Draw' => 'textarea','Option' =>array('vocab' => array('c506'),'cols' => 20,'rows'=>3),),
array('Column' =>'c507', 'Draw' => 'textarea','Option' =>array('vocab' => array('c507'),'cols' => 20,'rows'=>3),),
array('Column' =>'c508', 'Draw' => 'textarea','Option' =>array('vocab' => array('c508'),'cols' => 20,'rows'=>3),),
array('Column' =>'c509', 'Draw' => 'textarea','Option' =>array('vocab' => array('c509'),'cols' => 20,'rows'=>3),),
array('Column' =>'c510', 'Draw' => 'textarea','Option' =>array('vocab' => array('c510'),'cols' => 20,'rows'=>3),),
array('Column' =>'c511', 'Draw' => 'textarea','Option' =>array('vocab' => array('c511'),'cols' => 20,'rows'=>3),),
array('Column' =>'c512', 'Draw' => 'textarea','Option' =>array('vocab' => array('c512'),'cols' => 20,'rows'=>3),),
array('Column' =>'c513', 'Draw' => 'textarea','Option' =>array('vocab' => array('c513'),'cols' => 20,'rows'=>3),),
array('Column' =>'c514', 'Draw' => 'textarea','Option' =>array('vocab' => array('c514'),'cols' => 20,'rows'=>3),),
array('Column' =>'c515', 'Draw' => 'textarea','Option' =>array('vocab' => array('c515'),'cols' => 20,'rows'=>3),),
array('Column' =>'c516', 'Draw' => 'textarea','Option' =>array('vocab' => array('c516'),'cols' => 20,'rows'=>3),),
array('Column' =>'c517', 'Draw' => 'textarea','Option' =>array('vocab' => array('c517'),'cols' => 20,'rows'=>3),),
array('Column' =>'c518', 'Draw' => 'textarea','Option' =>array('vocab' => array('c518'),'cols' => 20,'rows'=>3),),
array('Column' =>'c519', 'Draw' => 'textarea','Option' =>array('vocab' => array('c519'),'cols' => 20,'rows'=>3),),
array('Column' =>'c520', 'Draw' => 'textarea','Option' =>array('vocab' => array('c520'),'cols' => 20,'rows'=>3),),
array('Column' =>'cc10', 'Draw' => 'textarea','Option' =>array('vocab' => array('cc10'),'cols' => 20,'rows'=>3),),
array('Column' =>'cc11', 'Draw' => 'textarea','Option' =>array('vocab' => array('cc11'),'cols' => 20,'rows'=>3),),
array('Column' =>'cc12', 'Draw' => 'textarea','Option' =>array('vocab' => array('cc12'),'cols' => 20,'rows'=>3),),
array('Column' =>'cc13', 'Draw' => 'textarea','Option' =>array('vocab' => array('cc13'),'cols' => 20,'rows'=>3),),
array('Column' =>'cc14', 'Draw' => 'textarea','Option' =>array('vocab' => array('cc14'),'cols' => 20,'rows'=>3),),
array('Column' =>'cc15', 'Draw' => 'textarea','Option' =>array('vocab' => array('cc15'),'cols' => 20,'rows'=>3),),
array('Column' =>'cc16', 'Draw' => 'textarea','Option' =>array('vocab' => array('cc16'),'cols' => 20,'rows'=>3),),
array('Column' =>'cc17', 'Draw' => 'textarea','Option' =>array('vocab' => array('cc17'),'cols' => 20,'rows'=>3),),
array('Column' =>'cc18', 'Draw' => 'textarea','Option' =>array('vocab' => array('cc18'),'cols' => 20,'rows'=>3),),
array('Column' =>'cc19', 'Draw' => 'textarea','Option' =>array('vocab' => array('cc19'),'cols' => 20,'rows'=>3),),
array('Column' =>'cc20', 'Draw' => 'textarea','Option' =>array('vocab' => array('cc20'),'cols' => 20,'rows'=>3),),
array('Column' =>'cc21', 'Draw' => 'textarea','Option' =>array('vocab' => array('cc21'),'cols' => 20,'rows'=>3),),
array('Column' =>'cc22', 'Draw' => 'textarea','Option' =>array('vocab' => array('cc22'),'cols' => 20,'rows'=>3),),
array('Column' =>'cc30', 'Draw' => 'textarea','Option' =>array('vocab' => array('cc30'),'cols' => 20,'rows'=>3),),
array('Column' =>'cc31', 'Draw' => 'textarea','Option' =>array('vocab' => array('cc31'),'cols' => 20,'rows'=>3),),
array('Column' =>'cc32', 'Draw' => 'textarea','Option' =>array('vocab' => array('cc32'),'cols' => 20,'rows'=>3),),
array('Column' =>'cc33', 'Draw' => 'textarea','Option' =>array('vocab' => array('cc33'),'cols' => 20,'rows'=>3),),
array('Column' =>'cc34', 'Draw' => 'textarea','Option' =>array('vocab' => array('cc34'),'cols' => 20,'rows'=>3),),
array('Column' =>'cc35', 'Draw' => 'textarea','Option' =>array('vocab' => array('cc35'),'cols' => 20,'rows'=>3),),
array('Column' =>'cc36', 'Draw' => 'textarea','Option' =>array('vocab' => array('cc36'),'cols' => 20,'rows'=>3),),
array('Column' =>'cc37', 'Draw' => 'textarea','Option' =>array('vocab' => array('cc37'),'cols' => 20,'rows'=>3),),
array('Column' =>'cc38', 'Draw' => 'textarea','Option' =>array('vocab' => array('cc38'),'cols' => 20,'rows'=>3),),
array('Column' =>'cc39', 'Draw' => 'textarea','Option' =>array('vocab' => array('cc39'),'cols' => 20,'rows'=>3),),
array('Column' =>'cc40', 'Draw' => 'textarea','Option' =>array('vocab' => array('cc40'),'cols' => 20,'rows'=>3),),
array('Column' =>'cc400', 'Draw' => 'textarea','Option' =>array('vocab' => array('cc400'),'cols' => 20,'rows'=>3),),
array('Column' =>'cc401', 'Draw' => 'textarea','Option' =>array('vocab' => array('cc401'),'cols' => 20,'rows'=>3),),
array('Column' =>'cc402', 'Draw' => 'textarea','Option' =>array('vocab' => array('cc402'),'cols' => 20,'rows'=>3),),
array('Column' =>'cc403', 'Draw' => 'textarea','Option' =>array('vocab' => array('cc403'),'cols' => 20,'rows'=>3),),
array('Column' =>'cc404', 'Draw' => 'textarea','Option' =>array('vocab' => array('cc404'),'cols' => 20,'rows'=>3),),
array('Column' =>'cc405', 'Draw' => 'textarea','Option' =>array('vocab' => array('cc405'),'cols' => 20,'rows'=>3),),
array('Column' =>'cc406', 'Draw' => 'textarea','Option' =>array('vocab' => array('cc406'),'cols' => 20,'rows'=>3),),
array('Column' =>'cc407', 'Draw' => 'textarea','Option' =>array('vocab' => array('cc407'),'cols' => 20,'rows'=>3),),
array('Column' =>'cc408', 'Draw' => 'textarea','Option' =>array('vocab' => array('cc408'),'cols' => 20,'rows'=>3),),
array('Column' =>'cc409', 'Draw' => 'textarea','Option' =>array('vocab' => array('cc409'),'cols' => 20,'rows'=>3),),
array('Column' =>'cc41', 'Draw' => 'textarea','Option' =>array('vocab' => array('cc41'),'cols' => 20,'rows'=>3),),
array('Column' =>'cc410', 'Draw' => 'textarea','Option' =>array('vocab' => array('cc410'),'cols' => 20,'rows'=>3),),
array('Column' =>'cc411', 'Draw' => 'textarea','Option' =>array('vocab' => array('cc411'),'cols' => 20,'rows'=>3),),
array('Column' =>'cc412', 'Draw' => 'textarea','Option' =>array('vocab' => array('cc412'),'cols' => 20,'rows'=>3),),
array('Column' =>'cc413', 'Draw' => 'textarea','Option' =>array('vocab' => array('cc413'),'cols' => 20,'rows'=>3),),
array('Column' =>'cc414', 'Draw' => 'textarea','Option' =>array('vocab' => array('cc414'),'cols' => 20,'rows'=>3),),
array('Column' =>'cc415', 'Draw' => 'textarea','Option' =>array('vocab' => array('cc415'),'cols' => 20,'rows'=>3),),
array('Column' =>'cc416', 'Draw' => 'textarea','Option' =>array('vocab' => array('cc416'),'cols' => 20,'rows'=>3),),
array('Column' =>'cc417', 'Draw' => 'textarea','Option' =>array('vocab' => array('cc417'),'cols' => 20,'rows'=>3),),
array('Column' =>'cc418', 'Draw' => 'textarea','Option' =>array('vocab' => array('cc418'),'cols' => 20,'rows'=>3),),
array('Column' =>'cc42', 'Draw' => 'textarea','Option' =>array('vocab' => array('cc42'),'cols' => 20,'rows'=>3),),
array('Column' =>'cc51', 'Draw' => 'textarea','Option' =>array('vocab' => array('cc51'),'cols' => 20,'rows'=>3),),
array('Column' =>'cc52', 'Draw' => 'textarea','Option' =>array('vocab' => array('cc52'),'cols' => 20,'rows'=>3),),
array('Column' =>'cc53', 'Draw' => 'textarea','Option' =>array('vocab' => array('cc53'),'cols' => 20,'rows'=>3),),
array('Column' =>'cc530', 'Draw' => 'textarea','Option' =>array('vocab' => array('cc530'),'cols' => 20,'rows'=>3),),
array('Column' =>'cc531', 'Draw' => 'textarea','Option' =>array('vocab' => array('cc531'),'cols' => 20,'rows'=>3),),
array('Column' =>'cc532', 'Draw' => 'textarea','Option' =>array('vocab' => array('cc532'),'cols' => 20,'rows'=>3),),
array('Column' =>'cc54', 'Draw' => 'textarea','Option' =>array('vocab' => array('cc54'),'cols' => 20,'rows'=>3),),
array('Column' =>'cc55', 'Draw' => 'textarea','Option' =>array('vocab' => array('cc55'),'cols' => 20,'rows'=>3),),
array('Column' =>'cc56', 'Draw' => 'textarea','Option' =>array('vocab' => array('cc56'),'cols' => 20,'rows'=>3),),
array('Column' =>'cc57', 'Draw' => 'textarea','Option' =>array('vocab' => array('cc57'),'cols' => 20,'rows'=>3),),
array('Column' =>'cc58', 'Draw' => 'textarea','Option' =>array('vocab' => array('cc58'),'cols' => 20,'rows'=>3),),
array('Column' =>'cc59', 'Draw' => 'textarea','Option' =>array('vocab' => array('cc59'),'cols' => 20,'rows'=>3),),
array('Column' =>'cc60', 'Draw' => 'textarea','Option' =>array('vocab' => array('cc60'),'cols' => 20,'rows'=>3),),
array('Column' =>'cc61', 'Draw' => 'textarea','Option' =>array('vocab' => array('cc61'),'cols' => 20,'rows'=>3),),
array('Column' =>'cc62', 'Draw' => 'textarea','Option' =>array('vocab' => array('cc62'),'cols' => 20,'rows'=>3),),
array('Column' =>'cc63', 'Draw' => 'textarea','Option' =>array('vocab' => array('cc63'),'cols' => 20,'rows'=>3),),
array('Column' =>'cc64', 'Draw' => 'textarea','Option' =>array('vocab' => array('cc64'),'cols' => 20,'rows'=>3),),
array('Column' =>'cc65', 'Draw' => 'textarea','Option' =>array('vocab' => array('cc65'),'cols' => 20,'rows'=>3),),
array('Column' =>'cc66', 'Draw' => 'textarea','Option' =>array('vocab' => array('cc66'),'cols' => 20,'rows'=>3),),
array('Column' =>'cc67', 'Draw' => 'textarea','Option' =>array('vocab' => array('cc67'),'cols' => 20,'rows'=>3),),
array('Column' =>'cc70', 'Draw' => 'textarea','Option' =>array('vocab' => array('cc70'),'cols' => 20,'rows'=>3),),
array('Column' =>'cc71', 'Draw' => 'textarea','Option' =>array('vocab' => array('cc71'),'cols' => 20,'rows'=>3),),
array('Column' =>'cc72', 'Draw' => 'textarea','Option' =>array('vocab' => array('cc72'),'cols' => 20,'rows'=>3),),
array('Column' =>'cc73', 'Draw' => 'textarea','Option' =>array('vocab' => array('cc73'),'cols' => 20,'rows'=>3),),
array('Column' =>'cc74', 'Draw' => 'textarea','Option' =>array('vocab' => array('cc74'),'cols' => 20,'rows'=>3),),
array('Column' =>'cc76', 'Draw' => 'textarea','Option' =>array('vocab' => array('cc76'),'cols' => 20,'rows'=>3),),
array('Column' =>'cc77', 'Draw' => 'textarea','Option' =>array('vocab' => array('cc77'),'cols' => 20,'rows'=>3),),
array('Column' =>'cc78', 'Draw' => 'textarea','Option' =>array('vocab' => array('cc78'),'cols' => 20,'rows'=>3),),
array('Column' =>'cc79', 'Draw' => 'textarea','Option' =>array('vocab' => array('cc79'),'cols' => 20,'rows'=>3),),
array('Column' =>'cc90', 'Draw' => 'textarea','Option' =>array('vocab' => array('cc90'),'cols' => 20,'rows'=>3),),
array('Column' =>'cc91', 'Draw' => 'textarea','Option' =>array('vocab' => array('cc91'),'cols' => 20,'rows'=>3),),
array('Column' =>'cc92', 'Draw' => 'textarea','Option' =>array('vocab' => array('cc92'),'cols' => 20,'rows'=>3),),
array('Column' =>'cc93', 'Draw' => 'textarea','Option' =>array('vocab' => array('cc93'),'cols' => 20,'rows'=>3),),
array('Column' =>'cc94', 'Draw' => 'textarea','Option' =>array('vocab' => array('cc94'),'cols' => 20,'rows'=>3),),
array('Column' =>'cc95', 'Draw' => 'textarea','Option' =>array('vocab' => array('cc95'),'cols' => 20,'rows'=>3),),
array('Column' =>'k100', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'k1000', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'k1001', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'k1002', 'Draw' => 'enum', 'Enum' => mk_enum($__otatest2_exam_enum),),
array('Column' =>'k1003', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'k1004', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'k1005', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'k1006', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'k1007', 'Draw' => 'static','Option' =>array('size' => 10),), 
array('Column' =>'k101', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'k102', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'k103', 'Draw' => 'static','Option' =>array('size' => 10),), 
array('Column' =>'k104', 'Draw' => 'static','Option' =>array('size' => 10),), 
array('Column' =>'k105', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'k106', 'Draw' => 'static','Option' =>array('size' => 10),), 
array('Column' =>'k107', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'k200', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'k201', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'k202', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'k203', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'k204', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'k300', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'k301', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'k302', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'k400', 'Draw' => 'static','Option' =>array('size' => 10),), 
array('Column' =>'k401', 'Draw' => 'enum', 'Enum' => mk_enum($__otatest2_hantei_enum),),
array('Column' =>'k402', 'Draw' => 'enum', 'Enum' => mk_enum($__otatest2_hantei_enum),),
array('Column' =>'k403', 'Draw' => 'enum', 'Enum' => mk_enum($__otatest2_hantei_enum),),
array('Column' =>'k404', 'Draw' => 'enum', 'Enum' => mk_enum($__otatest2_hantei_enum),),
array('Column' =>'k405', 'Draw' => 'enum', 'Enum' => mk_enum($__otatest2_hantei_enum),),
array('Column' =>'k406', 'Draw' => 'enum', 'Enum' => mk_enum($__otatest2_hantei_enum),),
array('Column' =>'k407', 'Draw' => 'enum', 'Enum' => mk_enum($__otatest2_hantei_enum),),
array('Column' =>'k408', 'Draw' => 'enum', 'Enum' => mk_enum($__otatest2_hantei_enum),),
array('Column' =>'k409', 'Draw' => 'enum', 'Enum' => mk_enum($__otatest2_hantei_enum),),
array('Column' =>'k410', 'Draw' => 'enum', 'Enum' => mk_enum($__otatest2_hantei_enum),),
array('Column' =>'k411', 'Draw' => 'enum', 'Enum' => mk_enum($__otatest2_hantei_enum),),
array('Column' =>'k412', 'Draw' => 'enum', 'Enum' => mk_enum($__otatest2_hantei_enum),),
array('Column' =>'k413', 'Draw' => 'enum', 'Enum' => mk_enum($__otatest2_hantei_enum),),
array('Column' =>'k414', 'Draw' => 'enum', 'Enum' => mk_enum($__otatest2_hantei_enum),),
array('Column' =>'k415', 'Draw' => 'enum', 'Enum' => mk_enum($__otatest2_hantei_enum),),
array('Column' =>'k416', 'Draw' => 'enum', 'Enum' => mk_enum($__otatest2_hantei_enum),),
array('Column' =>'k417', 'Draw' => 'enum', 'Enum' => mk_enum($__otatest2_hantei_enum),),
array('Column' =>'k418', 'Draw' => 'enum', 'Enum' => mk_enum($__otatest2_hantei_enum),),
array('Column' =>'k500', 'Draw' => 'enum', 'Enum' => mk_enum($__otatest2_exam_enum),),
array('Column' =>'k501', 'Draw' => 'enum', 'Enum' => mk_enum($__otatest2_exam_enum),),
array('Column' =>'k502', 'Draw' => 'enum', 'Enum' => mk_enum($__otatest2_exam_enum),),
array('Column' =>'k503', 'Draw' => 'enum', 'Enum' => mk_enum($__otatest2_exam_enum),),
array('Column' =>'k504', 'Draw' => 'enum', 'Enum' => mk_enum($__otatest2_exam_enum),),
array('Column' =>'k505', 'Draw' => 'enum', 'Enum' => mk_enum($__otatest2_plus_enum),),
array('Column' =>'k506', 'Draw' => 'enum', 'Enum' => mk_enum($__otatest2_exam_enum),),
array('Column' =>'k507', 'Draw' => 'enum', 'Enum' => mk_enum($__otatest2_exam_enum),),
array('Column' =>'k508', 'Draw' => 'enum', 'Enum' => mk_enum($__otatest2_exam_enum),),
array('Column' =>'k509', 'Draw' => 'enum', 'Enum' => mk_enum($__otatest2_exam_enum),),
array('Column' =>'k510', 'Draw' => 'enum', 'Enum' => mk_enum($__otatest2_exam_enum),),
array('Column' =>'k511', 'Draw' => 'enum', 'Enum' => mk_enum($__otatest2_exam_enum),),
array('Column' =>'k512', 'Draw' => 'enum', 'Enum' => mk_enum($__otatest2_exam_enum),),
array('Column' =>'k513', 'Draw' => 'enum', 'Enum' => mk_enum($__otatest2_exam_enum),),
array('Column' =>'k514', 'Draw' => 'enum', 'Enum' => mk_enum($__otatest2_exam_enum),),
array('Column' =>'k515', 'Draw' => 'enum', 'Enum' => mk_enum($__otatest2_exam_enum),),
array('Column' =>'k516', 'Draw' => 'enum', 'Enum' => mk_enum($__otatest2_exam_enum),),
array('Column' =>'k517', 'Draw' => 'enum', 'Enum' => mk_enum($__otatest2_exam_enum),),
array('Column' =>'k518', 'Draw' => 'enum', 'Enum' => mk_enum($__otatest2_exam_enum),),
array('Column' =>'k519', 'Draw' => 'enum', 'Enum' => mk_enum($__otatest2_exam_enum),),
array('Column' =>'k520', 'Draw' => 'enum', 'Enum' => mk_enum($__otatest2_exam_enum),),
array('Column' =>'k80', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'k81', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'k82', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'k83', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'k84', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'k85', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'k86', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'k87', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'k88', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'k89', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'k90', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'k91', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'kk10', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'kk11', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'kk12', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'kk13', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'kk14', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'kk15', 'Draw' => 'enum', 'Enum' => mk_enum($__otatest2_plus_enum),),
array('Column' =>'kk20', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'kk21', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'kk22', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'kk30', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'kk31', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'kk32', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'kk33', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'kk34', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'kk35', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'kk36', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'kk37', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'kk38', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'kk39', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'kk40', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'kk41', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'kk42', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'kk50', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'kk51', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'kk52', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'kk53', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'kk530', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'kk531', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'kk532', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'kk54', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'kk540', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'kk541', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'kk542', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'kk55', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'kk56', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'kk57', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'kk58', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'kk59', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'kk60', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'kk61', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'kk62', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'kk63', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'kk64', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'kk65', 'Draw' => 'static','Option' =>array('size' => 10),), 
array('Column' =>'kk66', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'kk67', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'kk70', 'Draw' => 'enum', 'Enum' => mk_enum($__otatest2_abo_enum),),
array('Column' =>'kk71', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'kk72', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'kk73', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'kk74', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'kk75', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'kk76', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'kk77', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'kk78', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'kk79', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'kk90', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'kk91', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'kk92', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'kk93', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'kk94', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'kk95', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'p100', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'p1000', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'p1001', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'p1002', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'p1003', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'p1004', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'p1005', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'p1006', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'p1007', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'p101', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'p102', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'p103', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'p104', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'p105', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'p106', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'p107', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'p200', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'p201', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'p202', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'p203', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'p204', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'p300', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'p301', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'p302', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'p500', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'p501', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'p502', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'p503', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'p504', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'p505', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'p506', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'p507', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'p508', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'p509', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'p510', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'p511', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'p512', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'p513', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'p514', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'p515', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'p516', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'p517', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'p518', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'p519', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'p520', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'p80', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'p81', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'p82', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'p83', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'p84', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'p85', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'p86', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'p87', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'p88', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'p89', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'p90', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'p91', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'pp10', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'pp11', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'pp12', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'pp13', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'pp14', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'pp15', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'pp20', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'pp21', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'pp22', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'pp30', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'pp31', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'pp32', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'pp33', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'pp34', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'pp35', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'pp36', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'pp37', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'pp38', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'pp39', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'pp40', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'pp41', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'pp42', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'pp50', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'pp51', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'pp52', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'pp53', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'pp530', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'pp531', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'pp532', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'pp54', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'pp55', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'pp56', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'pp57', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'pp58', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'pp59', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'pp60', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'pp61', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'pp62', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'pp63', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'pp64', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'pp66', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'pp67', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'pp70', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'pp71', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'pp72', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'pp73', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'pp74', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'pp75', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'pp76', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'pp77', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'pp78', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'pp79', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'pp90', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'pp91', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'pp92', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'pp93', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'pp94', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'pp95', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'ss10', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'ss20', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'ss21', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'ss22', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'ss40', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'ss41', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'ss42', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'ss50', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'ss51', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'ss52', 'Draw' => 'text','Option' =>array('size' => 10),), 
array('Column' =>'ss53', 'Draw' => 'textarea','Option' =>array('vocab' => array('ss53'),'cols' => 20,'rows'=>3),),
array('Column' =>'ss54', 'Draw' => 'textarea','Option' =>array('vocab' => array('ss54'),'cols' => 20,'rows'=>3),),
array('Column' =>'ss55', 'Draw' => 'textarea','Option' =>array('vocab' => array('ss55'),'cols' => 20,'rows'=>3),),

array('Column' => 'patient','Draw' => NULL,'Option' => array('noedit' => 1, 'nodisp' => 1),),
	  
 
array('Column' => 'dos','Label' => '検診日','Draw' => 'date','Option' => array('list' => 1,'size'=>10),),
	    
array('Column' => 'order_date','Label' => 'CMB報告日','Draw' => 'date','Option' => array('list' => 1,'size'=>10),),
	   
 
 array('Column' => 'ss11','Draw' => 'enum','Option' => array('list' => 1,'size'=>5),'Enum' => array('0' => 'May update','1' => 'CMBdata completed', '2'=> '削除',)),
 

array('Column' => 'shiji', 'Draw' => 'enum', 'Option' => array(  'list' => 1,'size'=>10),
'Enum' => _lib_u_ota_kiroku2(),),

				   
array('Column' => 'preorderdate', 'Draw' => 'date','Option' => array('list' => 1,'size'=>10),),
	   
array('Column' => 'category','Draw' => 'enum','Enum' => $__otatest2_report_enum,),
	     
array('Column' => 'addition', 'Draw' => 'enum','Option' => array('size'=>10),'Enum' => mk_enum($__otatest2_addition_enum),),
	
array('Column' => 'h1','Label' => '','Draw' => 'enum','Enum' => mk_enum($__otatest2_exam_enum),),
array('Column' => 'h2','Label' => '','Draw' => 'enum','Enum' =>mk_enum($__otatest2_exam_enum),),
array('Column' => 'special_req',
	      'Label' => '総合コメント',
	      'Draw' => 'textarea',
	      'Option' => array('vocab' => array('special'),
			'cols' => 60,'list' => 1,'rows'=>5),
	      ),
array('Column' => 'notes',
	      'Label' => '備考',
	      'Draw' => 'textarea',
	      'Option' => array('vocab' => array('notes'),
				'cols' =>60,'rows'=>5),
	      ),
);

?>
